#! /bin/sh
# Autostart --------------------------------------------------
killall "blueberry-obex-agent"
killall "blueberry-tray"
killall "picom"
killall "dunst"
killall "nm-applet"
killall "firewall-applet"
killall "nitrogen"
killall "xapp"
killall "ati-spi"
killall "xfce4-power-manager"

sh ~/.screenlayout/monitor.sh &
/usr/bin/dunst &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dex -a -s /etc/xdg/autostart/:~/.config/autostart
pgrep -x picom > /dev/null || picom &
nm-applet --indicator &
pgrep -x sxhkd > /dev/null || sxhkd &
numlockx on
sh ~/.config/polybar/launch.sh

xsetroot -cursor_name left_ptr &

bspc monitor DisplayPort-0 -d I II III IV V VI VII
bspc monitor DisplayPort-2 -d VIII IX X

bspc config border_width	2
bspc config window_gap		8
bspc config top_padding		8

bspc config split_ratio          0.52
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false

bspc config focused_border_color        "#2FDE73"
bspc config normal_border_color         "#101313"
bspc config active_border_color         "#101313"
bspc config presel_feedback_color		"#008ce3"

for val in {0..9}; do
    bsp-layout set tiled $val
done
